app:
    jwt:
        expiration-ms: 3000000
        secret: mySecretKey123435732
server:
    port: 8081
spring:
    application:
        name: EmployeeDirectoryService
    datasource:
        password: MyPass4306@
        url: jdbc:mysql://localhost:3306/studentdatabase
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
