app:
    jwt:
        expiration-ms: 3000000
        secret: mySecretKey123435732
server:
    port: 8081
spring:
    application:
        name: EmployeeDirectoryService
    datasource:
        password: MyPass4306@
        url: jdbc:mysql://localhost:3306/studentdatabase
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                envers:
                    audit_table_suffix: "_AUD" # Default, can be customized
                    default_schema: "your_schema" # Optional
                    revision_field_name: "revision_id" # Matches your CustomAuditEntity
                    revision_type_field_name: "revision_type"
                    global_with_modified_flag: true # Track changed fields
                    store_data_at_delete: true # Store audit data when an entity is deleted

                jdbc:
                    time_zone: UTC
    flyway:
        enabled: true
        baselineOnMigrate: true
        locations: classpath:db/migration
        schemas: studentdatabase,audit_schema
        default-schema: studentdatabase
        table: flyway_schema_history

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
components:
    securitySchemes:
        basicAuth: # <-- arbitrary name for the security scheme
            type: http
            scheme: basic
security: # This applies basicAuth to all operations
    - basicAuth: []

